# Version of Docker Compose to use
version: "3"

# List of all the services
services:
  # Service to use the npm command
  npm:
    # Docker image to use for this service
    image: node:17.0.0
    # User defined by this image to use
    user: node
    # Current working directory in which to issue the commands
    working_dir: /home/node
    # Enable interactive shell
    tty: true
    # Enable sending input to the interactive shell
    stdin_open: true
    # Command to prefix when running this service
    entrypoint: npm
    # Volume to map
    volumes:
      # Local current folder mapped to the image's node user home folder
      - .:/home/node
